name: Deploy a particular service
description: Dynamically deploy a particular service
author: Jon Jensen
# inputs:
#   uses:
#     description: Action reference or path, e.g. `actions/setup-node@v3`
#     required: true
#   with:
#     description: 'JSON-ified `inputs` for the action, e.g. `{"node-version": "18"}`'
#     required: false
#     default: "{}"
# outputs:
#   outputs:
#     description: 'JSON-ified `outputs` from the action, e.g. `{"node-version": "v18.12.0", "cache-hit": true}`'
#     value: ${{ steps.run.outputs.outputs }}
runs:
  using: composite
  steps:
    - name: Deploy Service 01
      shell: bash
      run: |
        echo "Deploying service 01"

    - name: Deploy Service 02
      shell: bash
      run: |
        echo "Deploying service 02"        

    - name: Deploy Service 03
      shell: bash
      run: |
        echo "Deploying service 03"
        
    #     mkdir -p ./.tmp-dynamic-uses &&
    #     cat <<'DYNAMIC_USES_EOF' >./.tmp-dynamic-uses/action.yml
    #     outputs:
    #       outputs:
    #         value: ${{ '$' }}{{ toJSON(steps.run.outputs) }}
    #     runs:
    #       using: composite
    #       steps:
    #       - run: rm -rf ./.tmp-dynamic-uses
    #         shell: sh
    #       - name: Run
    #         id: run
    #         uses: ${{ inputs.uses }}
    #         with: ${{ inputs.with || '{}' }}
    #     DYNAMIC_USES_EOF
    # - name: Run
    #   id: run
    #   uses: ./.tmp-dynamic-uses
    # - name: Cleanup
    #   if: always() && steps.run.outcome != 'success'
    #   shell: bash
    #   run: rm -rf ./.tmp-dynamic-uses
