name: 'Set Up Environment Variables'
description: 'Sets up environment variables for all jobs'

inputs:
  vars_json:
    description: 'Vars as JSON.'
    required: true
  service_name:
    description: 'Name of the service'
    required: true
    
runs:
  using: 'composite'
  steps:    
    - name: Setup service env variables                          
      run: |                  
        echo "Hello"  
      shell: bash
