name: 'Set Up Environment Variables'
description: 'Sets up environment variables for all jobs'

inputs:
  vars_json:
    description: 'Vars as JSON.'
    required: true
  service_name:
    description: 'Name of the service'
    required: true
    
runs:
  using: 'composite'
  steps:    
    - name: Setup service env variables                          
      run: |                  
        VARS_OBJ=${{ fromJson(inputs.vars_json) }}
        
        echo $VARS_OBJ

        
        
        
        # echo "Setting common variables"              
        # COMMON_ENV_JSON=$(echo "${VARS_JSON}" | jq 'with_entries(select(.key | startswith("COMMON_")))')

        # echo ${COMMON_ENV_JSON}
        # echo ${COMMON_ENV_JSON} | jq -r 'to_entries[][]' | while read -r key; do
        #   read -r value
        #   echo "${key#'COMMON_'}=${value}" >> $GITHUB_ENV            
        # done          

        # echo "Setting service variables"
        # SERVICE_ENV_JSON=$(echo ${VARS_JSON} | jq 'with_entries(select(.key | startswith("SERVER_")))')

        # echo ${SERVICE_ENV_JSON} | jq -r 'to_entries[][]' | while read -r key; do
        #   read -r value
        #   echo "${key#'SERVER_'}=${value}" >> $GITHUB_ENV            
        # done          
      shell: bash
