name: 'Set Up Environment Variables'
description: 'Sets up environment variables for all jobs'

inputs:
  vars_json:
    description: 'Vars as JSON.'
    required: true
  service_name:
    description: 'Name of the service'
    required: true
    
runs:
  using: 'composite'
  steps:    
    # - name: Print all vars
    #     env:
    #       ENV_VARS: ${{ toJSON(vars) }}
    #     run: |
    #       echo ${ENV_VARS}

    - name: Read vars
      id: vars
      shell: bash
      run: |        
        VARS_TO=${{ toJSON(inputs.vars_json) }}
        echo $VARS_TO | tr -d " " 

        echo $VARS_TO | tr -d " " | tr -d "\n"

        echo $VARS_TO | tr -d " " | tr -d "\n" | jq -r '.'

        # echo $VARS_TO | tr -d ' ' | tr -d '\\n' | sed 's/\\"/"/g

        # echo $VARS_TO | tr -d ' ' | tr -d '\\n' | sed 's/\\"/"/g | jq -r '.'        
        
        # VARS_JSON=$(echo $VARS_OBJ | jq -c)
        # echo "$VARS_OBJ" | tr -d ' ' | tr -d '\n'
        # echo "$VARS_OBJ" | tr -d ' '| tr -d '\n' | jq -c '.'
        
        # for key in "${!VARS_OBJ[@]}"; do
        #   echo "$key"
        # done
      
    # - name: Setup service env variables       
    #   shell: bash
    #   run: |                          
    #     echo ${{ steps.vars.outputs.ENV_VARS }}
    #     # VARS_OBJ=${{ fromJson(inputs.vars_json) }}
    #     # echo $VARS_OBJ
        
    #     # echo "${{ inputs.vars_json }}"        
                              
    #     # echo "Setting common variables"              
    #     # COMMON_ENV_JSON=$(echo $VARS_JSON | jq 'with_entries(select(.key | startswith("COMMON_")))')

    #     # echo $COMMON_ENV_JSON
    #     # echo ${COMMON_ENV_JSON} | jq -r 'to_entries[][]' | while read -r key; do
    #     #   read -r value
    #     #   echo "${key#'COMMON_'}=${value}" >> $GITHUB_ENV            
    #     # done          

    #     # echo "Setting service variables"
    #     # SERVICE_ENV_JSON=$(echo ${VARS_JSON} | jq 'with_entries(select(.key | startswith("SERVER_")))')

    #     # echo ${SERVICE_ENV_JSON} | jq -r 'to_entries[][]' | while read -r key; do
    #     #   read -r value
    #     #   echo "${key#'SERVER_'}=${value}" >> $GITHUB_ENV            
    #     # done        
      
