name: 'Set Up Environment Variables'
description: 'Sets up environment variables for all jobs'
runs:
  using: 'composite'
  steps:
    - name: Setup env variables
      run: |
        echo "APP_NAME=exampleAPP" >> $GITHUB_ENV
        echo "API_TIMEOUT=30" >> $GITHUB_ENV
      shell: bash
