name: 'Set Up Environment Variables'
description: 'Sets up environment variables for all jobs'

inputs:
  vars_json:
    description: 'Vars as JSON.'
    required: true
  service_name:
    description: 'Name of the service'
    required: true
    
runs:
  using: 'composite'
  steps:          
    - name: Setup service env variables       
      shell: bash
      run: |             
        VARS_JSON=${{ inputs.vars_json }}
        echo ${VARS_JSON}
                              
        echo "Setting common variables"   
        prefix="COMMON_"
        COMMON_ENV_JSON=$(echo ${VARS_JSON} | jq --arg PREFIX ${prefix} 'with_entries(select(.key | startswith($PREFIX)))')

        echo $COMMON_ENV_JSON
        echo ${COMMON_ENV_JSON} | jq -r 'to_entries[][]' | while read -r key; do
          read -r value
          echo "${key#'COMMON_'}=${value}" >> $GITHUB_ENV            
        done          

        echo "Setting service variables"
        prefix=${{ inputs.service_name }} + "_"
        echo "Filtering by $prefix"
        SERVICE_ENV_JSON=$(echo ${VARS_JSON} | jq --arg PREFIX ${prefix} 'with_entries(select(.key | startswith($PREFIX)))')

        echo ${SERVICE_ENV_JSON} | jq -r 'to_entries[][]' | while read -r key; do
          read -r value
          echo "${key#'SERVER_'}=${value}" >> $GITHUB_ENV            
        done        
      
