name: CI
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: | 
          echo ${{ github.event_name }}
      
      - name: Output GitHub event for debugging
        run: |
          echo "GitHub Event Payload:"
          echo '${{ toJson(github.event) }}'
