name: Server

on:
  workflow_call:
    secrets:
      password:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Debug
        run: echo ${{ secrets.password }}
