name: Deploy
run-name: Deploying ${{ inputs.service }} service(s) to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: "The target environment for deployment"
        options:
          - dev
          - staging
          - test
          - production
        default: "dev"
      service:
        required: true
        type: choice
        description: Choose the service to deploy
        options:
          - all
          - audit
          - backup
          - api
          - database
          - notification
          - reporting        

jobs:
  audit:
    name: Audit
    uses: ./.github/workflows/deploy-individual-service.yml
    with:
      service: audit
      environment: ${{ inputs.environment }}
  
  backup:
    name: Backup
    uses: ./.github/workflows/deploy-individual-service.yml
    with:
      service: backup
      environment: ${{ inputs.environment }}

  api:
    name: Api
    uses: ./.github/workflows/deploy-individual-service.yml
    with:
      service: api
      environment: ${{ inputs.environment }}

  database:
    name: Database
    uses: ./.github/workflows/deploy-individual-service.yml
    with:
      service: database
      environment: ${{ inputs.environment }}

  notification:
    name: Notification
    uses: ./.github/workflows/deploy-individual-service.yml
    with:
      service: notification
      environment: ${{ inputs.environment }}
      
  reporting:
    name: Reporting
    uses: ./.github/workflows/deploy-individual-service.yml
    with:
      service: reporting
      environment: ${{ inputs.environment }}
