name: Deploy
run-name: Deploying to ${{ inputs.project }}-${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: choice
        description: Choose the project to deploy
        options:
          - server
          - reporting
          - auditing
      environment:
        required: true
        type: choice
        description: "The target environment for deployment"
        options:
          - dev
          - staging
          - test
          - production
        default: "dev"

jobs:
  deploy:
    name: Deploy

    # environment:
    #   name: "${{ inputs.project }}-${{ inputs.environment }}"
    uses: ./.github/workflows/deploy-${{ inputs.environment }}.yml
    
    # runs-on: ubuntu-latest
    # env:
    #   IMAGE_TAG: ${{ inputs.tag_name || github.sha }}

    # steps:
    #   - name: Checkout Code
    #     uses: actions/checkout@v4        

    #   - name: Deploy
    #     run: |
    #       echo "Deploying to ${{ vars.APP_NAME }}-${{ inputs.environment }}"
