name: Deploy
run-name: Deploying to ${{ inputs.project }}-${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      # project:
      #   required: true
      #   type: choice
      #   description: Choose the project to deploy
      #   options:
      #     - server
      #     - auditing
      #     - backup
      #     - reporting
      #     - notification
      environment:
        required: true
        type: choice
        description: "The target environment for deployment"
        options:
          - dev
          - staging
          - test
          - production
        default: "dev"

jobs:
  server:
    name: Server
    uses: ./.github/workflows/deploy-server.yml
    with:
      environment: ${{ inputs.environment }}

  # reporting:
  #   name: Reporting
  #   uses: ./.github/workflows/deploy-reporting.yml
  #   with:
  #     environment: ${{ inputs.environment }}
    
    # steps:
    #   - name: Checkout Code
    #     uses: actions/checkout@v4        

    #   - name: Deploy
    #     run: |
    #       echo "Deploying to ${{ vars.APP_NAME }}-${{ inputs.environment }}"
